kind: Deployment
apiVersion: apps/v1
metadata:
  name: car-insurance-frontend
  namespace: default
  labels:
    app: car-insurance-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-insurance-frontend
  template:
    metadata:
      labels:
        app: car-insurance-frontend
    spec:
      containers:
        - name: car-insurance-frontend
          image: car-insurance-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: car-insurance-frontend
  name: car-insurance-frontend-service
spec:
  type: ClusterIP
  ports:
    - name: car-insurance-frontend-service-port-name
      port: 80
      protocol: TCP
  selector:
    app: car-insurance-frontend
